### ISSUE TITLE
`runtest.sh` fails

### ISSUE THREAD

**Issue by shinsa82** [ldltools/scxmlrun#3]
When executed in `scxmlrun-dev` container, `runtest.sh` (say, in `examples/echo`) fails due to lack of `$USER`.

```
root@eb62965bd388:~/scxmlrun/examples/echo# ./runtest.sh echo.in
js: hello
js: world
./runtest.sh: line 74: USER: unbound variable
```

Use of `$(id -u -n)` is recommended.

**Comment by ldltools** [comment]
fixed (1a2856b)
